### ISSUE TITLE
Logging in using OIDC while an existing emailadres (non-OIDC account) is present exists leads to a 500 error

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/mozilla-django-oidc-db#60]
Encountered with OpenZaak, 1.7.3-maykinlatest

UniqueViolation duplicate key value violates unique constraint "filled_email_unique"
DETAIL:  Key (email)=(<foo>) already exists.

https://sentry.maykinmedia.nl/organizations/maykin-media/issues/319027/?project=311&query=is%3Aunresolved

**Comment by sergei-maertens** [comment]
This is because of the claim mapping and which claim is used for the username field (defaults to `sub`).

In 0.11.0 this was tackled with this patch: 3a205292df2a443d9db8474ea5772d23073f73be which now at least gracefully displays an error, but ultimately it's down to the project itself to configure the mapping and unique constraints in a way that this can be prevented.
